FROM nginx:alpine

COPY index-test.html /usr/share/nginx/html/index.html

# Copy a custom Nginx configuration file
COPY frontend/nginx/nginx-test.conf /etc/nginx/conf.d/default.conf

# Expose port 443 for HTTPS
EXPOSE 443
