FROM nginx:alpine

COPY frontend/index-test.html /usr/share/nginx/html/index.html

# Copy a custom Nginx configuration file
COPY frontend/nginx/nginx-test.conf /etc/nginx/conf.d/default.conf

# Entry point script to handle SSL key generation and verification
COPY frontend/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Expose port 443 for HTTPS
EXPOSE 443

# Run the entrypoint script
ENTRYPOINT ["/entrypoint.sh"]