FROM nginx:alpine

COPY frontend/index-test.html /usr/share/nginx/html/index.html
COPY frontend/400-test.html /usr/share/nginx/html/400-test.html

# Copy a custom Nginx configuration file
COPY frontend/nginx/nginx-test.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]