version: '3.8'

services:
  backend:
    image: mixeway/flow-api:latest
    container_name: flowapi_backend
    ports:
      - "8888:8888"
      - "8443:8443"
    environment:
      SSL: "TRUE"
      # Uncomment and set these when using SSO
      # SSO: "TRUE"
      # SSO_CLIENT_ID: your_client_id
      # SSO_CLIENT_SECRET: your_client_secret
      # SSO_REDIRECT_URI: http://your-redirect-uri
      # SSO_AUTHORIZATION_URI: http://your-authorization-uri
      # SSO_TOKEN_URI: http://your-token-uri
      # SSO_USER_INFO_URI: http://your-user-info-uri
      # SSO_JWK_SET_URI: http://your-jwk-set-uri
      # FRONTEND_URL: http://your-frontend-url
    volumes:
      - pki_data:/etc/pki
      - dependency_track_data:/root/.dependency-track
    depends_on:
      - flowdb
    restart: always  # Add this line
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  flowdb:
    image: postgres:latest
    container_name: flowdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flow
      POSTGRES_USER: flow_user
      POSTGRES_PASSWORD: flow_pass
    volumes:
      - flowdb_data:/var/lib/postgresql/data
  flow:
    image: mixeway/flow:latest
    container_name: flow_frontend
    ports:
      - "443:443"
    volumes:
      - flow_data:/etc/nginx/ssl
    depends_on:
      - backend

volumes:
  flowdb_data:
  flow_data:
  pki_data:
  dependency_track_data:
