name: 'Build and Deploy Docker Application'
description: 'Build Docker image from Dockerfile and deploy container with volumes'

inputs:
  container-name:
    description: 'Name of the container'
    required: true
  network-name:
    description: 'Docker network to attach container to'
    required: true
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: './Dockerfile'
  build-context:
    description: 'Docker build context path'
    required: false
    default: '.'
  image-name:
    description: 'Name for the Docker image'
    required: true
  image-tag:
    description: 'Tag for the Docker image'
    required: false
    default: 'latest'
  exposed-ports:
    description: 'Ports to expose (format: 8080:8080,8443:8443)'
    required: true
  build-args:
    description: 'Build arguments (format: KEY1=value1,KEY2=value2)'
    required: false
    default: ''
  environment-vars:
    description: 'Environment variables (format: KEY1=value1,KEY2=value2)'
    required: false
    default: ''
  volumes:
    description: 'Volume mounts (format: volume1:/path1,volume2:/path2)'
    required: false
    default: ''
  named-volumes:
    description: 'Named volumes to create (format: vol1,vol2,vol3)'
    required: false
    default: ''
  health-check-url:
    description: 'URL to check after deployment'
    required: false
    default: ''
  depends-on:
    description: 'Container dependencies (comma-separated)'
    required: false
    default: ''

outputs:
  container-id:
    description: 'ID of the deployed container'
    value: ${{ steps.deploy.outputs.container_id }}
  image-id:
    description: 'ID of the built image'
    value: ${{ steps.build.outputs.image_id }}

runs:
  using: 'composite'
  steps:
    - name: Verify Dockerfile exists
      shell: bash
      run: |
        if [ ! -f "${{ inputs.dockerfile-path }}" ]; then
          echo "❌ Dockerfile not found: ${{ inputs.dockerfile-path }}"
          exit 1
        fi
        echo "✓ Dockerfile found: ${{ inputs.dockerfile-path }}"

    - name: Create named volumes
      if: inputs.named-volumes != ''
      shell: bash
      run: |
        echo "Creating named volumes..."
        IFS=',' read -ra VOLUMES <<< "${{ inputs.named-volumes }}"
        for vol in "${VOLUMES[@]}"; do
          vol=$(echo "$vol" | xargs) # trim whitespace
          if ! docker volume inspect "$vol" >/dev/null 2>&1; then
            docker volume create "$vol"
            echo "✓ Created volume: $vol"
          else
            echo "ℹ Volume already exists: $vol"
          fi
        done

    - name: Wait for dependencies
      if: inputs.depends-on != ''
      shell: bash
      run: |
        echo "Waiting for dependencies..."
        IFS=',' read -ra DEPS <<< "${{ inputs.depends-on }}"
        for dep in "${DEPS[@]}"; do
          dep=$(echo "$dep" | xargs)
          echo "Checking $dep..."
          
          for i in {1..30}; do
            if docker ps --format '{{.Names}}' | grep -q "^${dep}$"; then
              if [ "$(docker inspect -f '{{.State.Health.Status}}' $dep 2>/dev/null)" = "healthy" ] || \
                 [ "$(docker inspect -f '{{.State.Status}}' $dep 2>/dev/null)" = "running" ]; then
                echo "✓ $dep is ready"
                break
              fi
            fi
            [ $i -eq 30 ] && echo "⚠ Warning: $dep not ready, continuing anyway"
            sleep 2
          done
        done

    - name: Build Docker image
      id: build
      shell: bash
      run: |
        echo "Building Docker image..."
        echo "Image: ${{ inputs.image-name }}:${{ inputs.image-tag }}"
        
        BUILD_CMD="docker build"
        BUILD_CMD="$BUILD_CMD -t ${{ inputs.image-name }}:${{ inputs.image-tag }}"
        BUILD_CMD="$BUILD_CMD -f ${{ inputs.dockerfile-path }}"
        
        if [ -n "${{ inputs.build-args }}" ]; then
          IFS=',' read -ra ARGS <<< "${{ inputs.build-args }}"
          for arg in "${ARGS[@]}"; do
            arg=$(echo "$arg" | xargs)
            BUILD_CMD="$BUILD_CMD --build-arg $arg"
          done
        fi
        
        BUILD_CMD="$BUILD_CMD ${{ inputs.build-context }}"
        
        echo "Command: $BUILD_CMD"
        eval $BUILD_CMD
        
        IMAGE_ID=$(docker images -q ${{ inputs.image-name }}:${{ inputs.image-tag }})
        echo "image_id=$IMAGE_ID" >> $GITHUB_OUTPUT
        echo "✓ Image built: ${IMAGE_ID:0:12}"

    - name: Stop and remove existing container
      shell: bash
      run: |
        if docker ps -a --format '{{.Names}}' | grep -q "^${{ inputs.container-name }}$"; then
          echo "Stopping existing container..."
          docker stop ${{ inputs.container-name }} || true
          echo "Removing existing container..."
          docker rm ${{ inputs.container-name }} || true
          echo "✓ Existing container removed"
        else
          echo "ℹ No existing container to remove"
        fi

    - name: Deploy container
      id: deploy
      shell: bash
      run: |
        echo "Deploying container '${{ inputs.container-name }}'..."
        
        RUN_CMD="docker run -d"
        RUN_CMD="$RUN_CMD --name ${{ inputs.container-name }}"
        RUN_CMD="$RUN_CMD --network ${{ inputs.network-name }}"
        
        # Add ports
        if [ -n "${{ inputs.exposed-ports }}" ]; then
          IFS=',' read -ra PORTS <<< "${{ inputs.exposed-ports }}"
          for port in "${PORTS[@]}"; do
            port=$(echo "$port" | xargs)
            RUN_CMD="$RUN_CMD -p $port"
          done
        fi
        
        # Add environment variables
        if [ -n "${{ inputs.environment-vars }}" ]; then
          IFS=',' read -ra ENV_VARS <<< "${{ inputs.environment-vars }}"
          for env_var in "${ENV_VARS[@]}"; do
            env_var=$(echo "$env_var" | xargs)
            RUN_CMD="$RUN_CMD -e $env_var"
          done
        fi
        
        # Add volumes
        if [ -n "${{ inputs.volumes }}" ]; then
          IFS=',' read -ra VOLS <<< "${{ inputs.volumes }}"
          for vol in "${VOLS[@]}"; do
            vol=$(echo "$vol" | xargs)
            RUN_CMD="$RUN_CMD -v $vol"
          done
        fi
        
        RUN_CMD="$RUN_CMD --restart unless-stopped"
        
        # Add health check if URL provided
        if [ -n "${{ inputs.health-check-url }}" ]; then
          RUN_CMD="$RUN_CMD --health-cmd='curl -f ${{ inputs.health-check-url }} || exit 1'"
          RUN_CMD="$RUN_CMD --health-interval=30s"
          RUN_CMD="$RUN_CMD --health-timeout=10s"
          RUN_CMD="$RUN_CMD --health-retries=3"
          RUN_CMD="$RUN_CMD --health-start-period=60s"
        fi
        
        RUN_CMD="$RUN_CMD ${{ inputs.image-name }}:${{ inputs.image-tag }}"
        
        echo "Command: $RUN_CMD"
        CONTAINER_ID=$(eval $RUN_CMD)
        
        echo "container_id=$CONTAINER_ID" >> $GITHUB_OUTPUT
        echo "✓ Container deployed: ${CONTAINER_ID:0:12}"

    - name: Wait for container to start
      shell: bash
      run: |
        echo "Waiting for container to start..."
        sleep 5
        
        if ! docker ps --format '{{.Names}}' | grep -q "^${{ inputs.container-name }}$"; then
          echo "❌ Container failed to start!"
          echo "Container logs:"
          docker logs ${{ inputs.container-name }}
          exit 1
        fi
        
        echo "✓ Container is running"

    - name: Health check
      if: inputs.health-check-url != ''
      shell: bash
      run: |
        echo "Performing health check..."
        echo "URL: ${{ inputs.health-check-url }}"
        
        MAX_ATTEMPTS=30
        ATTEMPT=0
        
        while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
          if curl -f -s "${{ inputs.health-check-url }}" >/dev/null 2>&1; then
            echo "✓ Health check passed!"
            break
          fi
          
          ATTEMPT=$((ATTEMPT + 1))
          echo "Attempt $ATTEMPT/$MAX_ATTEMPTS - waiting..."
          sleep 2
        done
        
        if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
          echo "⚠ Health check timeout, checking container..."
          docker logs --tail 30 ${{ inputs.container-name }}
        fi

    - name: Display deployment info
      shell: bash
      run: |
        echo ""
        echo "=== Deployment Summary ==="
        echo "Container: ${{ inputs.container-name }}"
        echo "Image: ${{ inputs.image-name }}:${{ inputs.image-tag }}"
        echo "Network: ${{ inputs.network-name }}"
        echo ""
        docker ps --filter name=${{ inputs.container-name }} \
          --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
        echo ""
        echo "=== Recent Logs ==="
        docker logs --tail 15 ${{ inputs.container-name }}
        echo "========================"