name: "Slack Notify"
description: "Send Slack notification via webhook"

inputs:
  status:
    description: "Job status"
    required: true
  workflow:
    description: "Workflow name"
    required: true
  branch:
    description: "Branch name"
    required: true
  actor:
    description: "Triggered by"
    required: true
  custom_message:
    description: "Optional custom message"
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        STATUS="${{ inputs.status }}"

        if [ "$STATUS" = "success" ]; then
          EMOJI="✅"
        elif [ "$STATUS" = "failure" ]; then
          EMOJI="❌"
        else
          EMOJI="⚠️"
        fi

        MESSAGE="${EMOJI} Workflow *${{ inputs.workflow }}* completed with status: *${STATUS}*
        Branch: \`${{ inputs.branch }}\`
        Actor: ${{ inputs.actor }}
        ${{ inputs.custom_message }}"

        curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"${MESSAGE}\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
