name: Docker Build and Push

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    on:
      push:
        paths:
          - 'backend/**'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          cd backend
          docker build -t mixeway/flow-api:latest .
          docker push mixeway/flow-api:latest

  build-and-push-frontend:
    runs-on: ubuntu-latest
    on:
      push:
        paths:
          - 'frontend/**'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        run: |
          cd frontend
          docker build -t mixeway/flow:latest .
          docker push mixeway/flow:latest
