name: Docker Build and Push

on:
  push:
    paths:
      - 'backend/**'

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Java 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 22
      - name: Build and test with Maven and profile ut
        run: |
          cd backend
          mvn clean test -Dspring.profiles.active=ut
  

  build-and-push-backend:
    runs-on: ubuntu-latest
    needs: unit-testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          cd backend
          docker build -t mixeway/flow-api:latest .
          docker push mixeway/flow-api:latest
